route:
  receiver: cybelynxcore-default
  group_by:
    - alertname
    - severity
    - service
  routes:
    - matchers:
        - severity="critical"
      receiver: cybelynxcore-critical

receivers:
  - name: cybelynxcore-default
  - name: cybelynxcore-critical
