image:
  repository: <registry-url>/<project-name>/app
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  port: 8000

ingress:
  enabled: true
  host: <application-hostname>
  tls: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
