apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cybelynxcore-api
  namespace: cybelynxcore-production
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: cybelynxcore-api
